openai:
  api_key: ${OPENAI_API_KEY}
  model_name: "gpt-4o-mini"

paths:
  excel_file: "D:/Python test/RAG/mobile_forensic_data.xlsx"
  audio_folder: "D:/Python test/RAG/audio_to_text_files"
  image_folder: "D:/Python test/RAG/image_to_text_files"
  crime_fact_path: "D:/Python test/RAG/범죄사실2.txt"

vectorstore:
  chunk_size: 1000
  chunk_overlap: 200

logging:
  level: INFO
  format: '%(asctime)s - %(levelname)s - %(message)s'

rag:
  prompt_template: |
    당신은 범죄 수사를 위한 전문 분석가입니다. 
    주어진 범죄사실을 바탕으로 데이터(엑셀 파일과 텍스트 파일들)에서 관련 정보를 탐색하세요.

    범죄사실:
    {crime_fact}

    다음 사항에 주의를 기울이세요:
    1. 범죄사실에 언급된 모든 인물과 관련된 정보를 찾으세요.
    2. 범죄사실에 언급된 시간대의 사건과 관련된 모든 정보를 탐색하세요.
    3. 살인, 폭행, 또는 범죄사실과 관련된 행위를 암시하는 표현을 찾으세요.
    4. 범죄 은폐나 뒷처리를 암시하는 표현을 찾으세요.
    5. 각 정보의 출처(파일명)를 반드시 기록하세요.

    특별 지시사항:
    - 'image_to_text_files' 폴더 내의 모든 .txt 파일을 면밀히 검토하세요. 
    - 이 파일들은 이미지에서 추출된 텍스트로, 중요한 증거를 포함할 가능성이 높습니다.
    - 파일 내용의 길이나 형식이 일반적인 텍스트 파일과 다를 수 있으므로, 짧은 내용이라도 주의 깊게 살펴보세요.

    질문: {question} 
    컨텍스트: {context} 
    
    답변:
    1. 범죄사실 관련 인물들의 탐지 정보:
    2. 범죄사실 관련 시간대의 사건 정보:
    3. 범죄 관련 행위 탐지 정보:
    4. 범죄 은폐 관련 탐지 정보:
    5. 각 정보의 출처(파일명):
    6. 추가 설명 (필요시):

agents:
  별건_살인죄_분석가:
    backstory: 당신은 텍스트에서 폭행, 살인죄와 관련된 내용을 탐지하는 전문가입니다. 범죄사실 파일의 내용을 참고하여 관련 정보를 찾습니다.

  살인_보고서_작성자:
    backstory: 당신은 복잡한 정보를 종합하여 명확하고 통찰력 있는 한국어 보고서를 작성하는 전문가입니다.

tasks:
  별건_살인죄_탐지:
    description: |
      RAG 도구를 사용하여 제공된 범죄사실을 바탕으로 모든 엑셀 파일과 텍스트 파일을 검토하고, 관련 내용을 탐지하세요. 다음 사항에 주의를 기울이세요:
      1. 범죄사실에 언급된 모든 인물과 관련된 정보
      2. 범죄사실에 언급된 시간대의 사건과 관련된 모든 정보
      3. 살인, 폭행, 또는 범죄사실과 관련된 행위를 암시하는 표현
      4. 범죄 은폐나 뒷처리를 암시하는 표현
      5. 각 정보의 출처(파일명)를 반드시 기록하세요.
      6. 'image_to_text_files' 폴더 내의 모든 .txt 파일을 철저히 검토하세요. 이 파일들의 내용을 상세히 보고하고, 
      범죄와 관련될 수 있는 모든 정보를 추출하세요. 파일명에 관계없이 모든 파일을 동등하게 중요하게 취급하세요.
      
    expected_output: |
      1. 범죄사실 관련 인물들의 탐지 정보 (각 내용의 출처 파일명 포함)
      2. 범죄사실 관련 시간대의 사건 정보 (각 내용의 출처 파일명 포함)
      3. 범죄 관련 행위 탐지 정보 (각 내용의 출처 파일명 포함)
      4. 범죄 은폐 관련 탐지 정보 (각 내용의 출처 파일명 포함)
      5. 각 탐지 내용에 대한 간단한 설명


  별건_살인죄_보고서_작업:
    description: |
      별건_살인죄_탐지 task에서 얻은 정보와 범죄사실을 비교 분석하여 종합적이고 명확한 최종 보고서를 작성하세요. 보고서는 다음 내용을 포함해야 합니다:
      1. 범죄사실 요약
      2. 탐지된 정보 요약
      3. 범죄사실과 탐지된 정보의 비교 분석
      4. 사건의 상세 개요: 확인된 시간, 장소, 관련자
      5. 사건의 시간순 진행 재구성
      6. 관련자들의 행동과 역할 분석
      7. 범죄 은폐 시도로 보이는 정보 정리
      8. 추가 조사가 필요한 사항 제시
      9. 전체적인 사건에 대한 추론 및 결론
      
      보고서 작성 시 다음 지침을 준수하세요:
      - 모든 내용을 한글로 작성하세요.
      - 각 정보의 출처(파일명)를 명확히 밝히세요.
      - 확실한 사실과 추정을 구분하여 기술하세요.
      - 탐지된 모든 관련 정보를 누락 없이 포함하세요.
      - 범죄사실과 탐지된 정보 사이에 불일치가 있다면 이를 명확히 기술하세요.
      - 'image_to_text_files' 폴더에서 발견된 모든 정보를 특별히 강조하여 분석하고 보고하세요. 
      이 정보들은 이미지에서 추출된 것으로, 높은 증거 가치를 가질 수 있습니다.

    expected_output: |
      종합적이고 명확한 최종 보고서 (범죄사실 요약, 탐지 정보 요약, 비교 분석, 사건 상세 개요, 시간순 진행, 
      관련자 분석, 범죄 은폐 시도 정보, 추가 조사 필요 사항, 전체적 추론 및 결론, 범죄사실과의 불일치 사항. 
      모든 정보의 출처 명시. 한글로 작성.)